# Generated by Django 3.2.23 on 2023-12-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231219_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_time_min',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='created_at'),
        ),
    ]
