# Generated by Django 3.2.23 on 2023-12-23 22:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231223_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.post_image_file_path),
        ),
    ]
